# Generated by Django 6.1 on 2026-09-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('LANDLORD', 'LandLord'), ('TENANT', 'Tenant')], max_length=30),
        ),
    ]
